let mapleader = "\<Space>"

set nocompatible

syntax on

set background=dark
colorscheme atom-dark-256
set encoding=utf-8
set tabstop=4
set expandtab
set number
set mouse=a

"highlight searches
set hlsearch

set history=200

"Shows incomplete command
set showcmd

"Shows menu when using tab completion
set wildmenu

"On z+enter keeps 5 lines on top
set scrolloff=5

"My mappings {
" - writing file
map <leader>w :w!<CR>
" leader y ->  yank clipboard
vmap <leader>y "+y
"}
